# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jsGM6qQM8cfD9YNumZmwb5EWvcnWULr
"""

!pip install requests beautifulsoup4 pandas openpyxl



import requests
from bs4 import BeautifulSoup
import pandas as pd

# Function to get the list of companies from a given Wikipedia category page
def get_companies_from_wikipedia_category(url):
    companies = []
    while url:
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        for li in soup.select('.mw-category-group ul li'):
            companies.append(li.text)
        next_page = soup.find('a', text='next page')
        url = 'https://en.wikipedia.org' + next_page['href'] if next_page else None
    return companies

# Function to get all companies listed on the NYSE, including delisted ones
def get_all_nyse_companies():
    base_url = "https://en.wikipedia.org/wiki/Category:Companies_listed_on_the_New_York_Stock_Exchange"
    delisted_url = "https://en.wikipedia.org/wiki/Category:Companies_formerly_listed_on_the_New_York_Stock_Exchange"

    listed_companies = get_companies_from_wikipedia_category(base_url)
    delisted_companies = get_companies_from_wikipedia_category(delisted_url)

    return listed_companies, delisted_companies

# Function to save the data to an Excel file
def save_to_excel(listed_companies, delisted_companies, filename):
    df_listed = pd.DataFrame(listed_companies, columns=["Company Name"])
    df_listed["Status"] = "Listed"

    df_delisted = pd.DataFrame(delisted_companies, columns=["Company Name"])
    df_delisted["Status"] = "Delisted"

    df_all = pd.concat([df_listed, df_delisted], ignore_index=True)
    df_all.to_excel(filename, index=False)

# Main function to execute the script
def main():
    listed_companies, delisted_companies = get_all_nyse_companies()

    if listed_companies or delisted_companies:
        save_to_excel(listed_companies, delisted_companies, "nyse_companies.xlsx")
        print("Data has been saved to nyse_companies.xlsx")
    else:
        print("No data to save.")

if __name__ == "__main__":
    main()